SPK_NAME = zashboard
SPK_VERS = 1.80.0
SPK_REV = 1
SPK_ICON = src/zashboard.png

DEPENDS = cross/zashboard

override ARCH=noarch

MAINTAINER = Zephyruso
DESCRIPTION = "A Dashboard Using Clash API"
DISPLAY_NAME = "zashboard"
CHANGELOG = "update to version 1.80.0"

LICENSE = GPLv3

REQUIRED_MIN_DSM = 7

SPK_DEPENDS = WebStation:Apache2.4

SYSTEM_GROUP = http

DSM_UI_DIR = app
DSM_UI_CONFIG = src/app/config

CONF_DIR = src/conf/

STARTABLE = no

include ../../mk/spksrc.spk.mk
